ACADEMIC_MANAGEMENT/ACADEMIC_MANAGEMENT/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('admin_general.urls')),
    path('',include('admin_employee.urls')),
]

ACADEMIC_MANAGEMENT/admin_general/urls.py
from django.urls import path
from . import views
urlpatterns = [
    
    path('base/', views.base,name='base'),
    
    path('admin_master_dep/', views.admin_master_dep,name='admin_master_department'),
    path('department_edit/', views.department_edit,name='department_edit'),
    path('department_update/', views.department_update,name='department_update'),
    path('department_delete/', views.department_delete,name='department_delete'),
    
    path('admin_master_des/', views.admin_master_des,name='admin_master_designation'), 
    path('designation_edit/', views.designation_edit,name='designation_edit'),
    path('designation_update/', views.designation_update,name='designation_update'),
    path('designation_delete/', views.designation_delete,name='designation_delete'),
    
    path('admin_master_qua/', views.admin_master_qua,name='admin_master_qualification'),
    path('qualification_edit/', views.qualification_edit,name='qualification_edit'),
    path('qualification_update/', views.qualification_update,name='qualification_update'),
    path('qualification_delete/', views.qualification_delete,name='qualification_delete'),
    
    path('admin_master_class/', views.admin_master_class,name='admin_master_class'),
    path('class_edit/', views.class_edit,name='class_edit'),
    path('class_update/', views.class_update,name='class_update'),
    path('class_delete/', views.class_delete,name='class_delete'),
    
    path('admin_master_division/', views.admin_master_division,name='admin_master_division'),
    path('division_edit/', views.division_edit,name='division_edit'),
    path('division_update/', views.division_update,name='division_update'),
    path('division_delete/', views.division_delete,name='division_delete'),
    
    path('admin_master_emp_category/', views.admin_master_emp_category,name='admin_master_emp_category'),
    path('employee_edit/', views.employee_edit,name='employee_edit'),
    path('employee_update/', views.employee_update,name='employee_update'),
    path('employee_delete/', views.employee_delete,name='employee_delete'),
   
   
    path('admin_master_subject/', views.admin_master_subject,name='admin_master_subject'),
    path('subject_edit/', views.subject_edit,name='subject_edit'),
    path('subject_update/', views.subject_update,name='subject_update'),
    path('subject_delete/', views.subject_delete,name='subject_delete'),
   
    

    
   

]

ACADEMIC_MANAGEMENT/admin_general/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
  Department_Name = models.CharField(max_length=255)
  Department_Code = models.CharField(max_length=50)
  Status = models.BooleanField(default=True)
  
class Designation(models.Model):
  Designation_Name = models.CharField(max_length=255)
  Designation_Code = models.CharField(max_length=255)
  Status = models.BooleanField(default=True)

class Qualification(models.Model):
  Qualification_Name = models.CharField(max_length=255)
  Status = models.BooleanField(default=True)
  
class Master_class(models.Model):
  Master_class_Name = models.CharField(max_length=255)
  Status = models.BooleanField(default=True)
  
class Division(models.Model):
  Division_Name = models.CharField(max_length=255)
  Status = models.BooleanField(default=True)

class Emp_category(models.Model):
  
  EMPLOYEE_CATEGORY_CHOICES=[
    (1,'Accountant'),
    (2,'Cafeteria'),
    (3,'Librarian'),
    (4,'Teacher'),
    (5,'Other'),
  
    
  ]
  Employee_Name = models.CharField(max_length=255)
  Employee_Area = models.IntegerField(choices=EMPLOYEE_CATEGORY_CHOICES)
  Status = models.BooleanField(default=True)
  
  
class Subject(models.Model):
  Subject_Name = models.CharField(max_length=100)
  Status = models.BooleanField(default=True)
  
class SubjectClass(models.Model):
  Subject_Id = models.ForeignKey("Subject",on_delete=models.CASCADE)
  Class_Id = models.ForeignKey("Master_class",on_delete=models.CASCADE)
  
  
  

ACADEMIC_MANAGEMENT/admin_general/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,JsonResponse
from django.template import loader
from .models import *
from django.conf import settings
# Create your views here.



def base(request):
  
  template = loader.get_template('base.html')
  return HttpResponse(template.render())
   
# ADMIN_MASTER_DEPARTMENT_STARTING
def admin_master_dep(request):
      error=""
      success=""
      
      if request.method == 'POST':
        department_name = request.POST.get('department_name').strip()
        department_code = request.POST.get('department_code').strip()

        # Validation checks
        if not department_name or not department_code:
          # Handle missing data error
            error="both fields are required"
            
        elif Department.objects.filter(Department_Name=department_name,Department_Code=department_code).exists():
          # Handle duplicate department name error
            error="Department Name and code are already exist"
                
        elif Department.objects.filter(Department_Name=department_name).exists():
          # Handle duplicate department name error
            error="Department Name already exist"
            
        elif Department.objects.filter(Department_Code=department_code).exists(): 
          # Handle duplicate department code error
            error="DEpartment Code already exist"
            
        # Save the data to the database
        else :
          department = Department(Department_Name=department_name, Department_Code=department_code)
          department.save()
          success="submitted"
          
      departments = Department.objects.all()
      return render(request, 'admin_master_department.html', {'departments': departments,'error_msg':error,'success_msg':success})

def department_edit(request):
  id_var=request.GET['id'] #db id
  response_data= Department.objects.get(id=id_var) 
  serialized_data={
    'name': response_data.Department_Name,
    'code': response_data.Department_Code,
    'status':1 if response_data.Status else 0,
  }
  return JsonResponse(serialized_data)

def department_update(request):
  # ///
  error=""
  success=""
  
  id=request.GET['id']
  name=request.GET['name']
  code=request.GET['code']
  status=request.GET['status']

  
  if not name or not code:
      error="both fields are required"
      
  elif Department.objects.filter(Department_Name=name,Department_Code=code).exclude(id=id).exists():
      error="Department Name and code are already exist" 
      
  elif Department.objects.filter(Department_Name=name).exclude(id=id).exists():
          # Handle duplicate department name error
      error="Department Name already exist"
            
  elif Department.objects.filter(Department_Code=code).exclude(id=id).exists(): 
          # Handle duplicate department code error
      error="Department Code already exist"
            
        # Save the data to the database
  else :
      department = Department.objects.get(id=id)
      department.Department_Name=name
      department.Department_Code=code
      department.Status=status
      department.save()
      success="updated successfully"
      

          
    
  return JsonResponse({'error_msg':error,'success_msg':success})


def department_delete(request):
   dlt_id=request.GET.get('id')
   try:
      department = Department.objects.get(id=dlt_id)
      department.delete()
      return JsonResponse({'success':'Department deleted successfully'})
   except Department.DoesNotExist:
      return JsonResponse({'error':'Department not found'}, status=404) 

  
# ADMIN_MASTER_DEPARTMENT_ENDING
# ADMIN_MASTER_DESIGNATION_STARTING

def admin_master_des(request):
      error=""
      success=""
      
      if request.method == 'POST':
        designation_name = request.POST.get('designation_name').strip()
        designation_code = request.POST.get('designation_code').strip()

        # Validation checks
        if not designation_name or not designation_code:
          # Handle missing data error
            error="both fields are required"
            
        elif Designation.objects.filter(Designation_Name=designation_name,Designation_Code=designation_code).exists():
          # Handle duplicate department name error
            error="Designation Name and code are already exist"
                
        elif Designation.objects.filter(Designation_Name=designation_name).exists():
          # Handle duplicate department name error
            error="Designation Name already exist"
            
        elif Designation.objects.filter(Designation_Code=designation_code).exists(): 
          # Handle duplicate department code error
            error="Designation Code already exist"
            
            
                    # Save the data to the database
        else :
          department = Designation(Designation_Name=designation_name, Designation_Code=designation_code)
          department.save()
          success="submitted"
          
      designations = Designation.objects.all()
      return render(request, 'admin_master_designation.html', {'designations': designations,'error_msg':error,'success_msg':success})

def designation_edit(request):
  id_var=request.GET['id'] #db id
  response_data= Designation.objects.get(id=id_var) 
  serialized_data={
    'name': response_data.Designation_Name,
    'code': response_data.Designation_Code,
    'status':1 if response_data.Status else 0,
  }
  return JsonResponse(serialized_data)

def designation_update(request):
  # ///
  error=""
  success=""
  
  id=request.GET['id']
  name=request.GET['name']
  code=request.GET['code']
  status=request.GET['status']

  
  if not name or not code:
      error="both fields are required"
      
  elif Designation.objects.filter(Designation_Name=name,Designation_Code=code).exclude(id=id).exists():
      error="Designation Name and code are already exist" 
      
  elif Designation.objects.filter(Designation_Name=name).exclude(id=id).exists():
          # Handle duplicate department name error
      error="Designation Name already exist"
            
  elif Designation.objects.filter(Designation_Code=code).exclude(id=id).exists(): 
          # Handle duplicate department code error
      error="Designation Code already exist"
            
        # Save the data to the database
  else :
      designation = Designation.objects.get(id=id)
      designation.Designation_Name=name
      designation.Designation_Code=code
      designation.Status=status
      designation.save()
      success="updated successfully"
      

          
    
  return JsonResponse({'error_msg':error,'success_msg':success})


def designation_delete(request):
   dlt_id=request.GET.get('id')
   try:
      designation = Designation.objects.get(id=dlt_id)
      designation.delete()
      return JsonResponse({'success':'Designation deleted successfully'})
   except Designation.DoesNotExist:
      return JsonResponse({'error':'Designation not found'}, status=404) 

    
  # ADMIN_MASTER_DESIGNATION_ENDING
  # ADMIN_MASTER_QUALIFICATION_STARTING

def admin_master_qua(request):
      error=""
      success=""
      
      if request.method == 'POST':
        qualification_name = request.POST.get('qualification_name').strip()
        
        # Validation checks
        if not qualification_name :
          # Handle missing data error
            error="both fields are required"
                
        elif Qualification.objects.filter(Qualification_Name=qualification_name).exists():
          # Handle duplicate department name error
            error="Department Name already exist"
            
                    # Save the data to the database
        else :
          qualification = Qualification(Qualification_Name=qualification_name)
          qualification.save()
          success="submitted"
          
      qualifications = Qualification.objects.all()
      return render(request, 'admin_master_qualification.html', {'qualifications': qualifications,'qua_error_msg':error,'qua_success_msg':success})

def qualification_edit(request):
  id_var=request.GET['id'] #db id
  response_data= Qualification.objects.get(id=id_var) 
  serialized_data={
    'name': response_data.Qualification_Name,
    'status':1 if response_data.Status else 0,
  }
  return JsonResponse(serialized_data)

def qualification_update(request):
  # ///
  error=""
  success=""
  
  id=request.GET['id']
  name=request.GET['name']
  status=request.GET['status']

  
  if not name :
      error="Name field required"
      
 
      
  elif Qualification.objects.filter(Qualification_Name=name).exclude(id=id).exists():
          # Handle duplicate department name error
      error="Department Name already exist"
            
 
            
        # Save the data to the database
  else :
      qualification = Qualification.objects.get(id=id)
      qualification.Qualification_Name=name
      qualification.Status=status
      qualification.save()
      success="updated successfully"
      

          
    
  return JsonResponse({'error_msg':error,'success_msg':success})


def qualification_delete(request):
   dlt_id=request.GET.get('id')
   try:
      qualification = Qualification.objects.get(id=dlt_id)
      qualification.delete()
      return JsonResponse({'success':'qualification deleted successfully'})
   except Qualification.DoesNotExist:
      return JsonResponse({'error':'qualification not found'}, status=404) 

  

  # ADMIN_MASTER_QUALIFICATION_ENDING
  # ADMIN_MASTER_CLASS_STARTING
  
def admin_master_class(request):
      error=""
      success=""
      
      if request.method == 'POST':
        class_name = request.POST.get('class_name').strip()
        
        # Validation checks
        if not class_name :
          # Handle missing data error
            error="both fields are required"
                

ACADEMIC_MANAGEMENT/admin_general/templates/admin_master_emp_category.html
{% extends "base.html" %}
{% block content %}
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="#">Master</a></li>                    
    <li class="active">Manage Employee Category</li>
</ul>
<!-- END BREADCRUMB -->  
<div class="content-frame-top">                        
    <div class="page-title">                    
        <h2><span class="fa fa-arrow-circle-o-left"></span> Manage Employee Category</h2>
    </div>                                      
    

    
</div>
<script>
    {% if success_msg %}
        {% comment %} <button class="btn btn-success" onclick="noty({text: 'Successful action', layout: 'topRight', type: 'success'});">{{success_msg}}</button> {% endcomment %}
        document.addEventListener('DOMContentLoaded', function () {
        noty({ text: '{{success_msg}}',timeout: 2000, layout: 'topRight', type: 'success'});
      });
        
    {% endif %}

    {% if error_msg %}
        document.addEventListener('DOMContentLoaded', function () {
        noty({ text: '{{error_msg}}',timeout: 2000, layout: 'topRight', type: 'error'});
      });
        
    {% endif %}

</script>
<form method="post" action="{% url 'admin_master_emp_category' %}">
    {% csrf_token %}
    



<div class="panel panel-default">
    <div class="panel-heading ui-draggable-handle">
        <h1 class="panel-title"><strong></strong><b>New Employee Category</b></h1> 
        <ul class="panel-controls">
            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
        </ul>
    </div>
    <div class="panel-body">

        <div class="block">                            
                                              
            <div class="col-md-6">
                <div>
                    <input type="text" name="employee_name" placeholder="Employee Category Name" class="form-control">
                </div>
                      
            </div>                                
            <div class="col-md-6">
                <select class="form-control" placeholder="Area" data-live-search="true"  name="employee_area">
                    <option value="0">Area</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_ACCOUNTENT}}">Accountant</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_CAFETERIA}}">Cafeteria</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_LIBRARIAN}}">Librarian</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_TEACHER}}">Teacher</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_OTHER}}">Other</option>
                                    
                </select>
                      
            </div>
                                                                                      
        </div>
    </div>
    
    <div class="panel-footer">
        <input type="reset" class="btn btn-default" value="Clear">                                    
        <button class="btn btn-primary pull-right">Submit</button>
    </div>
</div>
</form>
<div class="panel panel-default">
    <div class="panel-heading ui-draggable-handle">                                
        <h1 class="panel-title"><b>View Employee Category</b></h1>    
        <ul class="panel-controls">
            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
            <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
        </ul>                                
    </div>
    <div class="panel-body">
        {% comment %} <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer"><div class="dataTables_length" id="DataTables_Table_0_length"><label>Show <select name="DataTables_Table_0_length" aria-controls="DataTables_Table_0" class="form-control"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div><div id="DataTables_Table_0_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control " placeholder="" aria-controls="DataTables_Table_0"></label></div> {% endcomment %}
        <table class="table datatable dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
            <thead>
                <tr role="row"><th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column ascending" style="width: 198px;">#</th><th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 309px;">Employee Category Name</th><th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 148px;">Area</th><th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 70px;">Status</th><th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 137px;">Action</th></tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr role="row" class="{% cycle 'odd' 'even' %}" id="trow">
                    <td class="sorting_1">{{ forloop.counter }}</td>
                    <td>{{ employee.Employee_Name }}</td>
                    <td>{{ employee.get_Employee_Area_display }}</td>
                    <td>{% if employee.Status %}<span class="label label-success">Active</span>{% else %}<span class="label label-danger">Deactive</span>{% endif %}</td>
                    <td>
                        <button class="btn btn-primary btn-rounded"  onclick="edit_emp({{employee.id}});"><span id="spinner{{employee.id}}" class="fa fa-pencil"></span></button>
                        {% if employee.Status == 0 %}    
                            <button class="btn btn-primary btn-rounded" onClick="emp_delete_row({{employee.id}});"><span class="fa fa-trash-o"></span></button>
                            <input type="hidden" class="btn btn-default" id="delete_url_id" value="{{request.scheme}}://{{request.get_host}}/employee_delete">
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
                </tbody>
        </table>
        {% comment %} <div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">Showing 1 to 2 of 2 entries</div><div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate"><a class="paginate_button previous disabled" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" id="DataTables_Table_0_previous">Previous</a><span><a class="paginate_button current" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0">1</a></span><a class="paginate_button next" aria-controls="DataTables_Table_0" data-dt-idx="7" tabindex="0" id="DataTables_Table_0_next">Next</a></div></div> {% endcomment %}
    </div>

    <div class="modal" id="modal_basic" tabindex="-1" role="dialog" aria-labelledby="defModalHead" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true"></span>×<span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="defModalHead">Edit Employee Category</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                    <div class="col-md-6">
                        <input type="text" id="emp_name_id" placeholder="Employee Category Name" class="form-control">
                    </div>
                    <div class="col-md-6">
                        <select class="form-control" id="emp_area_id" data-live-search="true">
                            <option value="0">Area</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_ACCOUNTENT}}">Accountant</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_CAFETERIA}}">Cafeteria</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_LIBRARIAN}}">Librarian</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_TEACHER}}">Teacher</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_OTHER}}">Other</option>
                                    
                        </select>
                    </div><br></br>
                    
                    <div class="col-md-12">                                                                                
                        <select id="emp_status_id" class="form-control" data-live-search="true">
                            <option value="1">Active</option>
                            <option value="0">Deactive</option>
                        </select>
                    </div>
                   

                </div>
            </div>
                
            <div class="panel-footer">
                <button class="btn btn-default" data-dismiss="modal">Close</button>
                <input type="hidden" class="btn btn-default" id="url_id" value="{{request.scheme}}://{{request.get_host}}/employee_edit">
                <button class="btn btn-primary pull-right" onclick="update_emp()" id="disabled_btn">Update</button>
                <input type="hidden" id="edit_data">
                <input type="hidden" class="btn btn-default" id="update_url_id" value="{{request.scheme}}://{{request.get_host}}/employee_update">
            </div>
                
            </div>
        </div>
    </div>
</div>
<!-- MESSAGE BOX-->
<div class="message-box animated fadeIn" data-sound="alert" id="mb-remove-row">
    <div class="mb-container">
        <div class="mb-middle">
            <div class="mb-title"><span class="fa fa-times"></span> Remove <strong>Data</strong> ?</div>
            <div class="mb-content">
                <p>Are you sure you want to remove this row?</p>                    
                <p>Press Yes if you sure.</p>
            </div>
            <div class="mb-footer">
                <div class="pull-right">
                    <button class="btn btn-success btn-lg mb-control-yes">Yes</button>
                    <button class="btn btn-default btn-lg mb-control-close">No</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END MESSAGE BOX-->    
   
{% endblock content %}